const Users = require("../api/users/model");

// METHOD(GET) GET ALL USERS => /API/USERS

// METHOD(POST) CREATE A USER => /API/USERS

// METHOD(GET) GET USER BY ID => /API/USERS/:ID

// METHOD(DEL) DELETE A USER BY ID => /API/USERS/:ID

// METHOD(PUT) UPDATES A USERD BY ID => /API/USERS:ID
